FROM mcr.microsoft.com/dotnet/sdk:6.0 as build
COPY ./ /sourceCode
WORKDIR /sourceCode
RUN dotnet restore
RUN dotnet publish -c Release -o /app
COPY ./processor_py /app/processor_py

FROM mcr.microsoft.com/dotnet/aspnet:6.0 as server
# install worker client runtime
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    wget \
    gnupg \
    python3 \
    python3-pip && \
    apt-get install procps -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=build /app .
RUN pip install --no-cache-dir -r /app/processor_py/requirements.txt
# Set the entry point for the application
CMD ["dotnet", "WorkerSample.dll"]
