name: examples-builder
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04 , ubuntu-24.04 ]
        lang: [ dotnet, python, rust]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v4

    - name: Build
      run: dotnet build --configuration Release
      working-directory: ./examples_worker/${{ matrix.lang }}
