name: Integration Test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 */12 * * *'
jobs:
  Integration-Test:
    strategy:
      matrix:
        os: [ubuntu-22.04 , ubuntu-24.04 ]
        mqtype: [ rabbitmq,kafka ]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: docker-compose-initial
      run: docker-compose  -f ./docker-compose-${{ matrix.mqtype }}.yml --env-file ./${{ matrix.mqtype }}/env/.env up --build -d
      working-directory: ./src/tests/integrationTest

    # todo tradeworker can be parameter,
    - name: Start chaos script
      run: |
        chmod +x ./chaos_script.sh
        nohup ./chaos_script.sh 'tradeworker' > chaos_script.log 2>&1 &
      working-directory: ./src/tests/integrationTest/autoScript

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Load environment variables from .env file & Doing integration test
      run: |
        chmod +x ./autoScript/integration_test.sh
        ./autoScript/integration_test.sh
      working-directory: ./src/tests/integrationTest/${{ matrix.mqtype }}

    - name: docker stop
      run: docker stop $(docker ps -q)
      working-directory: ./src/tests/integrationTest

    - name: Upload chaos_script.log as artifact
      uses: actions/upload-artifact@v4
      with:
        name: chaos-script-log-${{ matrix.mqtype }}
        path: ./src/tests/integrationTest/autoScript/chaos_script.log
